### ISSUE TITLE
Only one extension seem to get bootstrapped.

### ISSUE THREAD

**Issue by seivan** [iocave/monkey-patch#3]
During development, I installed both monkey patch and customize-ui for testing purposes.
It seems like it would only load customize-ui and not my extension. 

There is a large chance that I am doing something wrong, but I was hoping you could test it yourself since you know better. 

This is not a problem when loading my scripts through config instead of the API - so it's not a show stopper for me. 

Btw, monkey-patch is a life saver, thank you.

**Comment by seivan** [comment]
I will upload in a second but maybe you can help me with getting the dev environment running.

My extension depends on monkey-patch, so I install monkey-patch as extension-dependencies don't work during development. 
Whenever I restart VSCode, monkey-patch seems to remove my extension from its boot loader.
When I then start debugging my extension (F5) it seems to update the monkey patch modules in globalStorage to include it. 
Then it asks to restart, once VSCode restarts, it then resets the monkey patch bootloader because my vscode doesn't really have my extension installed, it just loads it during F5 context (debugging). 


How is your workflow when working with CustomizeUI and testing/running it?

**Comment by knopp** [comment]
Well, the workflow is a bit tricky. You can use extension debugging to debug actual extension (i.e. whether it copies files to the right place), but you can't really use it for debugging actual monkey patched javascript, or the monkey patching process itself. Especially in your case when you need to patch code in the main process, and thus any change requires restart of entire vscode process.

So the actual extension code for customize-ui is very simple, it more or less only copies the injected files, register modules with monkey-patch extension and prompt for restart. There's not a whole lot to debug there :)

During development, I do the following:

* Use regular vscode for editing the files and compiling extension.ts, Use vscode insider for actual testing. That's because you may need to be restarting the entire vscode process
* Symlink the extension folder to ~/.vscode-insiders/extensions
* Symlink the injected files to  ~/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules (i.e. where they'd be normally copied by the extension). This ensures that when restarting vscode insiders, you always get fresh version. Otherwise the extension would have to detect change, copy the files and prompt for restart

For injected code in browser process, you can use javascript console to debug the code. For injected code in main process, console.log is probably your best option, you can see the messages when launching vscode from terminal. If you do more extensive work in the main process, you can build vscode yourself and debug it from another vscode process, but that's bit more involved.

**Comment by seivan** [comment]
@knopp If you want to try with another extension, I published https://github.com/seivan/swipe-to-navigate recently.

**Comment by knopp** [comment]
Is this still relevant? I have both swipe-to-navigate and customize-ui installed and they both seem to be bootstrapped (I can see the log message from swipe-to-navigate)

**Comment by seivan** [comment]
@knopp Perhaps not, but it was an issue under development. It seems when developing and running the debug session things are a bit wonky either with your approach or mine commented above.

But if they both work for you then I guess we can close this :)
